// maxime.talents — interactions partagées, contenus originaux
document.documentElement.classList.add('js');
const SEC=[["Juridique","Avocats, notaires, huissiers, juristes : 19 ans de spécialité et de vocabulaire métier.","JUR"], ["Tertiaire","Assistanat de direction, comptabilité, fonctions supports.","TER"], ["Audit en entreprise","Diagnostic RH et préconisations concrètes.","AUD"], ["Coaching candidats","CV, entretiens, posture : révélez votre potentiel.","COA"], ["Jeunes diplômés","Premier emploi qualifié, accompagnement renforcé.","JR"], ["Conseil RH","Un regard extérieur expérimenté sur vos équipes.","RH"]];
const ROLES=[["Juridique","Collaborateur — Cabinet d'avocats","Droit des affaires, suivi de dossiers, relation clients.","Monaco","CDI"],["Juridique","Juriste d'entreprise — Groupe","Contrats, conformité, gouvernance.","Nice","CDI"],["Juridique","Assistant notarial — Étude","Actes, suivi clients, rigueur.","Monaco","CDI"],["Tertiaire","Assistante de direction — Cabinet","Agenda, coordination, discrétion.","Nice","CDI"],["Tertiaire","Comptable — PME","Tenue, déclarations, clôtures.","Paris","CDI"],["Tertiaire","Office Manager — Scale-up","Opérations, fournisseurs, vie d'équipe.","Lyon","CDI"],["Juridique","Clerc d'huissier — Étude","Procédures, constats, terrain.","Nice","CDI"],["Tertiaire","Chargé RH — Groupe","Recrutement, onboarding, suivi.","Paris","CDI"],["Débutants","Junior — Cabinet d'avocats","Premier poste qualifié, mentorat Maxime.","Nice","CDI"]];
function initNav(){const h=document.getElementById('hd');const pr=document.getElementById('progress');const onS=()=>{if(h)h.classList.toggle('scrolled',scrollY>10);if(pr){const d=document.documentElement;const p=d.scrollTop/(d.scrollHeight-d.clientHeight||1);pr.style.width=(p*100)+'%'}const t=document.getElementById('top');if(t)t.classList.toggle('show',scrollY>700)};addEventListener('scroll',onS,{passive:true});onS();const b=document.getElementById('bg'),m=document.getElementById('mob');if(b&&m){b.onclick=()=>m.classList.toggle('open');m.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>m.classList.remove('open')))};const t=document.getElementById('top');if(t)t.onclick=()=>scrollTo({top:0,behavior:'smooth'})}
function initExtras(){const tt=document.getElementById('tt'),dots=document.getElementById('dots');if(tt&&dots){const max=()=>Math.max(0,tt.children.length-1);for(let i=0;i<=max();i++){const d=document.createElement('button');d.className='dot2';d.setAttribute('aria-label','Avis '+(i+1));d.onclick=()=>{TIDX=i;paint()};dots.appendChild(d)}const paint=()=>{tt.style.transform=`translateX(-${TIDX*100}%)`;[...dots.children].forEach((d,i)=>d.classList.toggle('act',i===TIDX));const ti=document.getElementById('ti');if(ti)ti.textContent=`${TIDX+1} / ${max()+1}`};window.__paintDots=paint;paint();setInterval(()=>{if(document.hidden)return;TIDX=TIDX>=max()?0:TIDX+1;paint()},6000)}document.querySelectorAll('form[data-lead]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();f.outerHTML='<div class="form-ok"><b>Message bien reçu.</b><p style="color:var(--mut)">Maxime vous répond sous 48h ouvrées.</p></div>'}))}
function initReveal(){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('on');io.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>io.observe(e));setTimeout(()=>document.querySelectorAll('.reveal').forEach(e=>e.classList.add('on')),2500)}
function initCounters(){const c=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;const el=e.target,n=+el.dataset.n;let s=0;const st=Math.max(1,Math.round(n/50));const t=setInterval(()=>{s+=st;if(s>=n){s=n;clearInterval(t)}el.textContent=s},22);c.unobserve(el)}),{threshold:.5});document.querySelectorAll('[data-n]').forEach(e=>c.observe(e))}
function initSectors(){const p=document.getElementById('pills');if(!p)return;const t=document.getElementById('st'),d=document.getElementById('sd'),v=document.getElementById('sv');function sel(i){[...p.children].forEach((e,j)=>e.classList.toggle('act',i===j));t.textContent=SEC[i][0];d.textContent=SEC[i][1];v.textContent=SEC[i][2]+' — VISUEL'}SEC.forEach((s,i)=>{const x=document.createElement('button');x.className='pill'+(i===0?' act':'');x.textContent=s[0];x.onclick=()=>sel(i);p.appendChild(x)});sel(0)}
function drawRoles(f=""){const box=document.getElementById('roles');if(!box)return;const list=ROLES.filter(r=>(r[0]+r[1]+r[2]+r[3]).toLowerCase().includes((f||"").toLowerCase()));box.innerHTML="";list.forEach(r=>{box.innerHTML+=`<div class="card"><span class="tag">${r[0]}</span><h3>${r[1]}</h3><p>${r[2]}</p><div style="display:flex;gap:12px;color:var(--mut);font-size:13px;font-weight:700"><span>${r[3]}</span><span>${r[4]}</span></div><a href="contact.html">Postuler →</a></div>`});if(!box.innerHTML)box.innerHTML='<div class="card"><h3>Aucun résultat</h3><p>Écrivez à Maxime, réseau caché actif.</p></div>';const rc=document.getElementById('rcount');if(rc)rc.textContent=list.length?list.length+" offre"+(list.length>1?"s":"")+" affichée"+(list.length>1?"s":""):"Aucune offre pour cette recherche"}
function initRoles(){const q=document.getElementById('q');let f="";try{f=sessionStorage.getItem('mq')||"";sessionStorage.removeItem('mq')}catch(_){}if(q&&f)q.value=f;drawRoles(q?q.value:"");if(q)q.addEventListener('input',e=>drawRoles(e.target.value))}
let TIDX=0;function slide(d){const t=document.getElementById('tt');if(!t)return;const max=t.children.length-1;TIDX=Math.max(0,Math.min(max,TIDX+d));if(window.__paintDots){window.__paintDots();return}t.style.transform=`translateX(-${TIDX*100}%)`;const ti=document.getElementById('ti');if(ti)ti.textContent=`${TIDX+1} / ${max+1}`}
document.addEventListener('DOMContentLoaded',()=>{initNav();initReveal();initCounters();initSectors();initRoles();initExtras()});
function filtrer(){const q=document.getElementById('q');try{sessionStorage.setItem('mq',q?q.value:"")}catch(_){}drawRoles(q?q.value:"")}